services:
  maltidsplanerare:
    build:
      context: .
      network: host
    container_name: maltidsplanerare
    restart: always
    network_mode: host
    volumes:
      - ./data:/app/data
    env_file:
      - .env
